### ISSUE TITLE
Documentation updates needed, when we run application on IBM Bluemix.

### ISSUE THREAD

**Issue by cvishal** [ibm-cloud-architecture/refarch-jee-customerorder#20]
Need to update documents to help end user execute installation of this app smoothly.

Please note following 2 issues were observed, one for existing documentation and second one was specifically for Cloud setup (Deploy this application on WASaaS (Bluemix WAS) and DashDB for analytics, on cloud.)

Problem 1 : User Creation scenario:
-----------------------------------
There are two steps mentioned:
1) Documentation asks us to create users, using addBusinessCustomer.sql and addResidentialCustomer.sql. And asks to create same user in the Security Registry. 
2) Towards the end, Test part of application does create few users (kbrown and rbarcia).
These two operations need to in sync, so that user kbrown and rbarcia would be created in Security Registry and same would be populated in DB, when Test part is ran.

Problem 2 : When using WASaaS and DashDB Service on Bluemix.
------------------------------------------------------------
We need to add a specific section to explain how to handle application deployment on Cloud.
Key points:
- As Bluemix trial account doesn't have permission to create 'DashDB for Transactions'. I used 'DashDB for Analytics', which is available with Free Tier.
- User need to create two instances for DashDB (one for ORDERDB and one for INDB), as one instance can have only one DB.
- createOrderDB.sql script failed with "DashDB for Analytics", as the default DB is Column Organised. Add key work "ORGANIZE BY ROW" while creating tables.
- While installing application, documentation says "Step 12. Customize the environment variables DBUNIT_SCHEMA, DBUNIT_USERNAME, and DBUNIT_PASSWORD fields. Its not very clear, as which DB instance is needed here. In case of two different DB instances, we need to give ORDERDB SCHEMA and user/pw details. 
- Also there are other Environment Variables, which need to be populated , such as CUSTOMER_ORDER_SERVICES_WEB_ENDPOINT and CUSTOMER_ORDER_SERVICES_TEST_ENDPOINT.

**Comment by jesusmah** [comment]
Problem 2 is addressed in #22

**Comment by jesusmah** [comment]
@cvishal please, check commit https://github.com/ibm-cloud-architecture/refarch-jee-customerorder/commit/2d24268e339d16670ba4287131b3e66f9b6791bd and let me know if it still confuses the user. Thanks

**Comment by cvishal** [comment]
This is good. Thanks.
