### ISSUE TITLE
Need Links and doc for VPN setup and public IP in Step 6 

### ISSUE THREAD

**Issue by kaschalk** [ibm-cloud-architecture/refarch-jee-customerorder#21]
Step 6: Create WebSphere Application Server service instance

1.Go to your Bluemix console and create a WebSphere Application Server instance

    Name your service, choose the WAS Base Plan, and create the instance.

    Provision your server based on your requirements.

    Once done, you can access the Admin console using the Open the Admin Console option. In order to access the Admin console, install the VPN as instructed. **Needs URL**

    Get a public IP address. This can be done using the Manage Public IP Access option. **Needs doc & link**

    You can ssh into the WebSphere Application Server instance using the Admin Username and Password provided in your instance.

**Comment by Hemankita** [comment]
Added the links and content.
