### ISSUE TITLE
config scripts

### ISSUE THREAD

**Issue by jesusmah** [ibm-cloud-architecture/refarch-jee-customerorder#25]
Need to automate the JPA specification for WAS9 dev-prod branches since envs come with JPA 2.1 version by default but we need to downgrade it to JPA 2.0 version. WASaaS instances need to be config likewise. Therefore, we need to update the myConfig.py script to configure JPA version appropriately and the WASaaS config scripts too.

The JPA configuration must look like the following:

<img width="1493" alt="screen shot 2017-06-23 at 12 40 46" src="https://user-images.githubusercontent.com/4761922/27478813-8b86f3f2-5811-11e7-96f7-dc4c6a6b2e81.png">

I've checked the WAS console to see what are the commands to carry the above out at seems to be the following:

AdminConfig.modify('(cells/CloudBurstCell_11495578906115/nodes/CloudBurstNode_11495578906115/servers/server1|server.xml#JavaPersistenceAPIService_1496851771238)', '[[defaultPersistenceProvider "com.ibm.websphere.persistence.PersistenceProviderImpl"] [defaultJTADataSourceJNDIName ""] [defaultNonJTADataSourceJNDIName ""]]')
AdminTask.modifyJPASpecLevel('server1(cells/CloudBurstCell_11495578906115/nodes/CloudBurstNode_11495578906115/servers/server1|server.xml)', '[-specLevel 2.0]')

However, in the first command, there are some attributes that I guess need to be env specific...

**Comment by Hemankita** [comment]
Updated the configuration scripts with JPA specification.
